x5engine.imQueue.push_init("x5engine.imDate('.imDate')");
x5engine.imQueue.push_init("x5engine.imHour('.imHour')");
x5engine.imQueue.push_init("x5engine.imAccess.showLogout()");
x5engine.imQueue.push_init("x5engine.utils.autoHeight()");
x5engine.imQueue.push_init("x5engine.imCart.updateWidget()");
x5engine.imQueue.push_init("x5engine.imCart.setupProductList()");
x5engine.imQueue.push_init("x5engine.imGrid.init()");
x5engine.imQueue.push_init("x5engine.imMenu.setup({ target: '#imMnMn', verticalScroll: false, orientation: 'horizontal', menuHeight: 22, submenuHeight: 22, opacity: 0.800, type: 'singleColumn', effect: 'fade'})",false);
x5engine.settings.imShowBox.effect = 'fade';
x5engine.settings.imShowBox.shadow = true;
x5engine.settings.imShowBox.background = '#000000';
x5engine.settings.imShowBox.borderRadius = 1;
x5engine.settings.imShowBox.textColor = '#000000';
x5engine.settings.imShowBox.boxColor = '#FFFFFF';
x5engine.settings.imShowBox.opacity = 0.700;
x5engine.settings.imShowBox.radialBg = true; // Works only in Mozilla Firefox and Google Chrome
x5engine.settings.imPopUp.effect = 'fade';
x5engine.settings.imPopUp.width = 500;
x5engine.settings.imPopUp.shadow = true;
x5engine.settings.imPopUp.background = '#000000';
x5engine.settings.imPopUp.borderRadius = 10;
x5engine.settings.imPopUp.textColor = '#000000';
x5engine.settings.imPopUp.boxColor = '#FFFFFF';
x5engine.settings.imPopUp.opacity = 0.700;
x5engine.settings.imTip.borderRadius = 5;
x5engine.settings.imTip.shadow = true;
x5engine.settings.imTip.arrow = true;
x5engine.settings.imTip.position = 'bottom';
x5engine.settings.imTip.effect = 'none';
x5engine.settings.imTip.showTail = true;
x5engine.settings.imCaptcha.offlineCodes[0] = { letter: 'H', path: 'captcha/imcpa_pr2.gif'};
x5engine.settings.imCaptcha.offlineCodes[1] = { letter: 'K', path: 'captcha/imcpa_87f.gif'};
x5engine.settings.imCaptcha.offlineCodes[2] = { letter: 'V', path: 'captcha/imcpa_ujm.gif'};
x5engine.settings.imCaptcha.offlineCodes[3] = { letter: 'E', path: 'captcha/imcpa_3wv.gif'};
x5engine.settings.imCaptcha.offlineCodes[4] = { letter: '8', path: 'captcha/imcpa_2jd.gif'};
x5engine.settings.imCaptcha.offlineCodes[5] = { letter: 'U', path: 'captcha/imcpa_34x.gif'};
x5engine.settings.imCaptcha.offlineCodes[6] = { letter: 'P', path: 'captcha/imcpa_7ty.gif'};
x5engine.settings.imCaptcha.offlineCodes[7] = { letter: 'E', path: 'captcha/imcpa_84j.gif'};
x5engine.settings.imCaptcha.offlineCodes[8] = { letter: 'C', path: 'captcha/imcpa_vy7.gif'};
x5engine.settings.imCaptcha.offlineCodes[9] = { letter: 'J', path: 'captcha/imcpa_dnf.gif'};
